# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-11-08 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
